name: CI Workflow for Terraform

on:
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infrastructure code
        uses: actions/checkout@v2

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Rewrite Terraform configuration files to a canonical format and style.
        run: terraform fmt -check -recursive

      - name: Validate Terraform code
        run: terraform validate
